USE STORE_DANI;

#ALTER TABLE people ADD COLUMN isActive BOOLEAN DEFAULT FALSE;



#INSERT INTO PERSON(FIRST_NAME,LAST_NAME, ADDRESS, DOCUMENT_TYPE_ID, DOCUMENT_NUMBER, PHONE,ID_ROL)
#VALUES('Andres','Rodriguez','V/Palermo Sur',5,'1127071425','3226440105',2);

#ALTER TABLE PERSON ADD COLUMN IS_ACTIVE BOOLEAN DEFAULT TRUE;

SELECT *FROM PERSON;