USE STORE_DANI;

DELETE FROM PRODUCT_CATEGORY WHERE PRODUCT_ID=9;
DELETE FROM PRODUCT WHERE ID_PRODUCT=9;

SELECT PRODUCT.ID_PRODUCT,PRODUCT.PRODUCT_NAME, PRODUCT.STOCK,PRODUCT.PRICE,
CATEGORY.CATEGORY_NAME, PRODUCT.ISACTIVO
 FROM CATEGORY
INNER JOIN PRODUCT_CATEGORY ON CATEGORY.ID_CATEGORY=PRODUCT_CATEGORY.CATEGORY_ID
inner JOIN PRODUCT ON PRODUCT_CATEGORY.PRODUCT_ID=PRODUCT.ID_PRODUCT;




