USE STORE_DANI;

INSERT INTO PERSON(FIRST_NAME,LAST_NAME, ADDRESS, DOCUMENT_TYPE_ID, DOCUMENT_NUMBER, PHONE)
VALUES('Camilo','Santacruz Gutierres','V/Palmenras',2,'1127071439','3227349085');

SELECT *FROM PERSON;