USE STORE_DANI;
#ALTER TABLE PRODUCT MODIFY COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


#SELECT *FROM PRODUCT_CATEGORY;

#DELETE FROM PRODUCT_CATEGORY WHERE PRODUCT_ID=40;
#DELETE FROM PRODUCT_CATEGORY WHERE PRODUCT_ID=41;
#DELETE FROM PRODUCT_CATEGORY WHERE PRODUCT_ID=42;

DELETE FROM PRODUCT WHERE ID=40;#42
DELETE FROM PRODUCT WHERE ID=41;
DELETE FROM PRODUCT WHERE ID=42;

SELECT *FROM PRODUCT;