
##TENER EN CUENTA EL DROP DATABASE
##DROP DATABASE IF EXISTS TIENDA_STORE;

CREATE DATABASE TIENDA_STORE;

use TIENDA_STORE;

CREATE TABLE TIPO_DNI (
  ID_TIPO_DNI INT AUTO_INCREMENT PRIMARY KEY,
  TIPO VARCHAR(45)
);

CREATE TABLE ROL (
  ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
  ROL VARCHAR(50),
  DESCRIPCION TINYTEXT
);

CREATE TABLE VENDEDOR (
  ID_VENDEDOR INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRES VARCHAR(40),
  APELLIDOS VARCHAR(35),
  TIPO_DNI INT,
  DNI VARCHAR(12),
  ROL INT,
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME,
  FOREIGN KEY (TIPO_DNI) REFERENCES TIPO_DNI(ID_TIPO_DNI),
  FOREIGN KEY (ROL) REFERENCES ROL(ID_ROL)
);


CREATE TABLE PEOPLE(
ID_PEOPLE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
DIRECCION VARCHAR(70),
TIPO_DNI INT,
DNI VARCHAR(12),
TELEFONO VARCHAR(12),
FECHA_CREACION TIMESTAMP,
FECHA_ACTUALIZACAION DATETIME,
FOREIGN KEY (TIPO_DNI) REFERENCES TIPO_DNI(ID_TIPO_DNI)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
ID_PEOPLE INT,
FOREIGN KEY (ID_PEOPLE) REFERENCES PEOPLE(ID_PEOPLE)
);

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50),
NIT VARCHAR(12),
TELEFONO VARCHAR(12),
FECHA_CREACION TIMESTAMP,
FECHA_ACTUALIZACION DATETIME
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR(50),
DESCRIPCION TINYTEXT
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
PRODUCTO VARCHAR(50),
STOCK INT,
PRECIO INT,
FECHA_CREACION TIMESTAMP,
FECHA_ACTUALIZACION DATETIME
);

CREATE TABLE CATEGORIA_PRODUCTO(
ID_PRODUCTO_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
ID_CATEGORIA INT,
ID_PRODUCTO INT,
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE PRODUCTO_PROVEEDOR(
ID_PRODUCTO_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO INT,
ID_PROVEEDOR INT,
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE ESTADO_FACTURA(
ID_ESTADO_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
ESTADO VARCHAR(50),
DESCRIPCION TINYTEXT
);

CREATE TABLE FACTURA(
ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT,
ID_ESTADO INT,
FECHA_CREACION TIMESTAMP,
FECHA_ACTUALIZACION DATETIME,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO_FACTURA(ID_ESTADO_FACTURA)
);

CREATE TABLE PRODUCTO_FACTURA(
ID_PRODUCTO_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO INT,
ID_FACTURA INT,
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
FOREIGN KEY(ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);

CREATE TABLE ESTADO_PEDIDO(
ID_ESTADO_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
ESTADO VARCHAR(45)
);

CREATE TABLE PEIDO(
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
ID_FACTURA INT,
ID_ESTADO INT,
DETALLES TINYTEXT,
FOREIGN KEY(ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO_PEDIDO(ID_ESTADO_PEDIDO)
);
